name: secrets
on: [workflow_dispatch]

jobs:
  build-with-secrets:
    runs-on: ubuntu-latest
    environment: test_env_1
    steps:
    - name: Log test secrets
      run: |
        token=${{ env.TEST_ENV }}
        echo $token
        echo ${token:0:5}
        echo ${token:5}
        token=${{ env.TEST_ENV }}
        echo $token
        echo ${token:0:5}
        echo ${token:5}
