name: test-vars

on: 
  workflow_dispatch:

jobs:
  display-variables:
    runs-on: ubuntu-latest
    environment: TEST_ENV
    steps:        
    - name: Use variables
      run: |
        echo "repo variable : ${{ vars.TEST_REPO_VAR }}"
        echo "org variable : ${{ vars.TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST_TEST }}"
        echo "overriden variable : ${{ vars.OVERRIDE_VAR }}"
        echo "env variable : ${{ vars.TEST_ENV }}"
